In [2]:
import numpy as np

In [4]:
my_list=[1,2,3]
my_Array=np.array([1,2,3])
type(my_list)

list

In [6]:
my_list=[1,2,3]
np.array(my_list)


array([1, 2, 3])

In [8]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [16]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
 np.ones(3)

array([1., 1., 1.])

In [20]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [24]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [26]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [28]:
print("Random")

Random


In [30]:
np.random.rand(2)

array([0.63411306, 0.99050196])

In [32]:
np.random.rand(2)

array([0.12300536, 0.25432168])

In [34]:
np.random.rand(5,5)

array([[0.54769644, 0.75458558, 0.60970989, 0.01826102, 0.70359395],
       [0.37328719, 0.57601457, 0.16651401, 0.04166354, 0.90861887],
       [0.36321235, 0.48072395, 0.66544212, 0.19284377, 0.73873444],
       [0.44545698, 0.18050277, 0.61795442, 0.94025314, 0.0623397 ],
       [0.57970725, 0.29406517, 0.1901525 , 0.63759193, 0.74212985]])

In [36]:
np.random.randn(2)

array([ 0.54292116, -1.03426135])

In [38]:
print("RANDINT")

RANDINT


In [40]:
np.random.randint(1,100)

69

In [44]:
np.random.randint(1,100,10)

array([61,  4,  5, 89,  6, 17,  6, 63,  1, 83])

In [46]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [54]:
arr=np.array(25)
ranarr=np.random.randint(0,50,10)
print(arr)
print(ranarr)

25
[29 37  1 20 32 11 21 43 24 48]


In [66]:
print(ranarr)

[29 37  1 20 32 11 21 43 24 48]


In [68]:
ranarr.max()

48

In [70]:
ranarr.min()

1

In [72]:
arr.shape

()

In [82]:
arr.dtype

dtype('int32')

In [84]:
arr2=np.array([1.2,3.4,5.6])
arr2.dtype

dtype('float64')

In [100]:
import numpy as np
arr=np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [102]:
arr[8]

8

In [110]:
arr[0:5]=100
#show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [118]:
arr=np.arange(0,11)
#show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [120]:
slice_of_arr=arr[0:6]
#show
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [122]:
slice_of_arr[:]=99
#show Sliceagain
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [124]:
arr_copy=arr.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [130]:
arr_2d=np.array(([5,10,15],[20,25,30],[35,40,45]))
#show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [132]:
arr_2d[1]

array([20, 25, 30])

In [136]:
arr_2d[1][2]

30

In [140]:
arr_2d[1,1]

25

In [142]:
arr_2d[2]

array([35, 40, 45])

In [148]:
arr_2d[0,:]

array([ 5, 10, 15])

In [150]:
arr=np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [152]:
arr>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [156]:
bool_arr=arr>4

bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [160]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [162]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [164]:
x=2
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [166]:
print("NUMPY OPERATIONS")

NUMPY OPERATIONS


In [21]:
import numpy as np

x=np.array([0,10])

print(type(x))



<class 'numpy.ndarray'>


In [184]:
print("Taking Universal Array")

Taking Universal Array


In [186]:
#Taking SquareRoots
np.sqrt(arr)

array([0.        , 3.16227766])

In [188]:
print("CALCULATING EXPONENTIAL (e*)")

CALCULATING EXPONENTIAL (e*)


In [190]:
np.exp(arr)

array([1.00000000e+00, 2.20264658e+04])

In [192]:
np.sin(arr)

array([ 0.        , -0.54402111])

In [194]:
np.log(arr)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_12812\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 2.30258509])

In [198]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [200]:
arr=np.arange(0,10)
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [202]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [204]:
arr/arr

C:\Users\ASUS\AppData\Local\Temp\ipykernel_12812\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [206]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [208]:
np.log(arr)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_12812\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [210]:
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [214]:
arr.sum()

45

In [218]:
arr.mean()

4.5

In [220]:
arr.max()

9

In [222]:
print("Series")

Series


In [22]:
import numpy as np

In [24]:
X=[10,20,30,40]
my_array=np.array(X)
type(X)

list

In [26]:
type(my_array)

numpy.ndarray

In [28]:
X[0]

10

In [30]:
my_array[0]

10

In [32]:
M1=np.array([[1,2,3],[4,5,6],[7,8,9]])


In [34]:
M1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
M2=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [38]:
M2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
M1@M2

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [42]:
mydata=np.arange(0,10,3)

In [44]:
print(mydata)

[0 3 6 9]


In [46]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [48]:
np.zeros([4,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [50]:
np.linspace(0,3,100)

array([0.        , 0.03030303, 0.06060606, 0.09090909, 0.12121212,
       0.15151515, 0.18181818, 0.21212121, 0.24242424, 0.27272727,
       0.3030303 , 0.33333333, 0.36363636, 0.39393939, 0.42424242,
       0.45454545, 0.48484848, 0.51515152, 0.54545455, 0.57575758,
       0.60606061, 0.63636364, 0.66666667, 0.6969697 , 0.72727273,
       0.75757576, 0.78787879, 0.81818182, 0.84848485, 0.87878788,
       0.90909091, 0.93939394, 0.96969697, 1.        , 1.03030303,
       1.06060606, 1.09090909, 1.12121212, 1.15151515, 1.18181818,
       1.21212121, 1.24242424, 1.27272727, 1.3030303 , 1.33333333,
       1.36363636, 1.39393939, 1.42424242, 1.45454545, 1.48484848,
       1.51515152, 1.54545455, 1.57575758, 1.60606061, 1.63636364,
       1.66666667, 1.6969697 , 1.72727273, 1.75757576, 1.78787879,
       1.81818182, 1.84848485, 1.87878788, 1.90909091, 1.93939394,
       1.96969697, 2.        , 2.03030303, 2.06060606, 2.09090909,
       2.12121212, 2.15151515, 2.18181818, 2.21212121, 2.24242

In [52]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [54]:
import numpy as np

In [56]:
np.random.rand(2)

array([0.77275052, 0.18407766])

In [60]:
np.random.rand(5,5)

array([[0.81199758, 0.56611064, 0.05794249, 0.54217615, 0.50635624],
       [0.46553938, 0.3735051 , 0.61810972, 0.43219532, 0.0376686 ],
       [0.00706584, 0.13329972, 0.8217647 , 0.70938531, 0.88076952],
       [0.14681739, 0.39490117, 0.46563048, 0.16604717, 0.03517763],
       [0.48005071, 0.92285099, 0.41076698, 0.83757586, 0.58506855]])

In [62]:
np.random.randn(2)

array([0.03342375, 2.15365291])

In [64]:
np.random.randint(10,20,6)

array([13, 10, 18, 16, 15, 18])

In [66]:
np.random.seed(30)
np.random.randint(10,20,7)

array([15, 15, 14, 17, 12, 15, 11])

In [68]:
mydata=np.random.randint(10,100,25)

In [70]:
len(mydata)

25

In [72]:
mydata.shape

(25,)

In [76]:
mynewdata=mydata.reshape(5,5)

In [78]:
mynewdata.shape

(5, 5)

In [80]:
updatedata=np.random.randint(10,20,6)

In [82]:
updatedata.shape

(6,)

In [84]:
updatedata

array([11, 17, 11, 19, 18, 15])

In [86]:
updatedata.max()

19

In [88]:
updatedata.min()

11

In [92]:
updatedata.argmax()

3

In [94]:
updatedata.dtype

dtype('int32')

In [102]:
L1=[10,20,30,40,"Jammu"]
D1=np.array(L1)

In [104]:
D1.dtype

dtype('<U11')

In [106]:
D1[0]

'10'

In [108]:
D1[4]

'Jammu'

In [110]:
mydata=np.random.randint(10,200,13)

In [112]:
mydata

array([195,  49, 147, 171, 130, 185, 177, 174,  32, 178, 163, 192, 129])

In [114]:
mydata>50

array([ True, False,  True,  True,  True,  True,  True,  True, False,
        True,  True,  True,  True])

In [116]:
mydata[mydata>100]

array([195, 147, 171, 130, 185, 177, 174, 178, 163, 192, 129])

In [118]:
mydata[mydata<100]

array([49, 32])

In [120]:
mydata[mydata!=113]

array([195,  49, 147, 171, 130, 185, 177, 174,  32, 178, 163, 192, 129])

In [122]:
import numpy as np

In [124]:
mydata=np.random.randint(10,200,8)

In [126]:
mydata

array([ 79, 115, 164, 101,  29, 168,  59,  62])

In [128]:
mydata/mydata

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [130]:
mydata=np.arange(0,10,2)

In [133]:
mydata

array([0, 2, 4, 6, 8])

In [135]:
mydata/mydata

C:\Users\ASUS\AppData\Local\Temp\ipykernel_10316\3970214447.py:1: RuntimeWarning: invalid value encountered in divide
  mydata/mydata


array([nan,  1.,  1.,  1.,  1.])

In [141]:
mydata2=np.arange(0,20,2)

In [143]:
mydata+mydata2

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36])

In [145]:
np.log(mydata)

C:\Users\ASUS\AppData\Local\Temp\ipykernel_10316\2923084688.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(mydata)


array([      -inf, 0.69314718, 1.38629436, 1.79175947, 2.07944154,
       2.30258509, 2.48490665, 2.63905733, 2.77258872, 2.89037176])

In [147]:
np.exp(mydata)

array([1.00000000e+00, 7.38905610e+00, 5.45981500e+01, 4.03428793e+02,
       2.98095799e+03, 2.20264658e+04, 1.62754791e+05, 1.20260428e+06,
       8.88611052e+06, 6.56599691e+07])

In [149]:
np.cos(mydata)

array([ 1.        , -0.41614684, -0.65364362,  0.96017029, -0.14550003,
       -0.83907153,  0.84385396,  0.13673722, -0.95765948,  0.66031671])

In [151]:
mydata

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])